Ckeditor::Asset.create!([
  {data_file_name: "nastol_com_ua_113908.jpg", data_content_type: "image/jpeg", data_file_size: 1186780, assetable_id: 1, assetable_type: "User", type: "Ckeditor::Picture", width: 2048, height: 1153},
  {data_file_name: "nastol_com_ua_113908.jpg", data_content_type: "image/jpeg", data_file_size: 1186780, assetable_id: 1, assetable_type: "User", type: "Ckeditor::Picture", width: 2048, height: 1153}
])
Menu.create!([
  {title: "Главное меню", place: "main_menu"},
  {title: "Меню в ленте", place: "news_menu"}
])
MenuItem.create!([
  {menu_id: 1, menu_item_id: 1, title: "Пример категории", link: "/product_categories/1", position: 1},
  {menu_id: 1, menu_item_id: 1, title: "Новости", link: "/post_categories/1", position: 2},
  {menu_id: 2, menu_item_id: 1, title: "Ссылка", link: "/", position: 1},
  {menu_id: 2, menu_item_id: 1, title: "Ссылка", link: "/", position: 2},
  {menu_id: 2, menu_item_id: 1, title: "Ссылка", link: "/", position: 3},
  {menu_id: 2, menu_item_id: 1, title: "Ссылка", link: "/", position: 4},
  {menu_id: 1, menu_item_id: 1, title: "Доставка и оплата", link: "/delivery_and_pay", position: 3},
  {menu_id: 1, menu_item_id: 1, title: "Контакты", link: "/contacts", position: 4}
])

Post.create!([
  {post_category_id: 1, title: "Новость 1", text: "<p><span style=\"color: #333333; font-family: 'Source Sans Pro', Arial; font-size: 14px; line-height: 20px; background-color: #e9f5fa;\">Интернет магаз<strong>ин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции</strong> и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности. Именно поэтому родители даже могут не сомневаться в том, что продукция, предложенная им, имеет всю нужную документацию от компаний-производителей и, соответственно, магазин предоставляет на любые товары гарантийный срок эксплуатации.&nbsp;</span></p>\r\n", lead: "Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого.", meta_title: "Title:", meta_description: "Description:", meta_keywords: "Keywords:", avatar_file_name: "blog01.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 27245, avatar_updated_at: "2015-05-08 01:19:50"},
  {post_category_id: 1, title: "Новость 2", text: "<p><span style=\"color: #333333; font-family: 'Source Sans Pro', Arial; font-size: 14px; line-height: 20px; background-color: #e9f5fa;\">Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности. Именно поэтому родители даже могут не сомневаться в том, что продукция, предложенная им, имеет всю нужную документацию от компаний-производителей и, соответственно, магазин предоставляет на любые товары гарантийный срок эксплуатации.&nbsp;</span></p>\r\n", lead: "Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого.", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: "blog02.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 16747, avatar_updated_at: "2015-05-08 01:19:58"},
  {post_category_id: 1, title: "Новость 3", text: "<p><span style=\"color: #333333; font-family: 'Source Sans Pro', Arial; font-size: 14px; line-height: 20px; background-color: #e9f5fa;\">Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности. Именно поэтому родители даже могут не сомневаться в том, что продукция, предложенная им, имеет всю нужную документацию от компаний-производителей и, соответственно, магазин предоставляет на любые товары гарантийный срок эксплуатации.&nbsp;</span></p>\r\n", lead: "Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого.", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: "blog01.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 27245, avatar_updated_at: "2015-05-08 01:20:05"},
  {post_category_id: 1, title: "Новость 4", text: "<p><span style=\"color: #333333; font-family: 'Source Sans Pro', Arial; font-size: 14px; line-height: 20px; background-color: #e9f5fa;\">Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности. Именно поэтому родители даже могут не сомневаться в том, что продукция, предложенная им, имеет всю нужную документацию от компаний-производителей и, соответственно, магазин предоставляет на любые товары гарантийный срок эксплуатации.&nbsp;</span></p>\r\n", lead: "Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого.", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: "blog02.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 16747, avatar_updated_at: "2015-05-08 01:20:18"}
])
PostCategory.create!([
  {title: "Новости", description: "<p>Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости Здесь будут новости</p>", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: "bl2.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 2035, avatar_updated_at: "2015-04-27 18:18:36"},
  {title: "Акционные предложения", description: "<p>Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp; Здесь описание категории&nbsp;&nbsp;</p>", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: "bl2.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 2035, avatar_updated_at: "2015-04-27 16:22:02"},
  {title: "Статьи для продвижения", description: "<p>Здесь статьи для продвижения</p>", meta_title: "", meta_description: "", meta_keywords: "", avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {title: "Название", description: "<p>Описание<strong> Описание Описание Описание Оп</strong>исание Описание Описание Описание Описание Описание Описание Описание&nbsp;</p>", meta_title: "title title title title title title title title title ", meta_description: "description description description description description description description description description description description ", meta_keywords: "keywods keywods keywods keywods keywods keywods keywods keywods keywods keywods keywods keywods keywods ", avatar_file_name: "nastol.com.ua_113908.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 1186780, avatar_updated_at: "2015-05-02 19:44:08"}
])
Product.create!([
  {product_category_id: 1, name: "Товар 1", description: "<p><strong>Описание товара</strong> Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товар</p>\r\n", sku: "12343", meta_title: "title", meta_description: "description", meta_keywords: "key", price: "12345678.0", avatar_file_name: "image06.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 26821, avatar_updated_at: "2015-05-07 00:53:56", avatar: nil},
  {product_category_id: 1, name: "Товар 2", description: "<p><strong>Описание товара</strong> Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товар</p>\r\n", sku: "122342", meta_title: "", meta_description: "", meta_keywords: "", price: "123456789.0", avatar_file_name: "image07.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 22258, avatar_updated_at: "2015-05-07 22:40:12", avatar: nil},
  {product_category_id: 1, name: "Товар 3", description: "<p><strong>Описание товара</strong> Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товара Описание товар</p>\r\n", sku: "123456", meta_title: "", meta_description: "", meta_keywords: "", price: "12345.0", avatar_file_name: "image06.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 26821, avatar_updated_at: "2015-05-07 22:40:31", avatar: nil}
])
ProductCategory.create!([
  {name: "Категория 1", description: "<p>Интернет магазин детских товаров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности.&nbsp;</p>", meta_title: "автомобили", meta_description: "Дескрипшен автомобилей", meta_keywords: "Ключевые слова для автомобилей", product_category_id: 1, image_file_name: "m5.jpg", image_content_type: "image/jpeg", image_file_size: 700692, image_updated_at: "2015-03-18 17:15:25", avatar_file_name: "product.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 779, avatar_updated_at: "2015-04-25 05:59:41"},
  {name: "Категория 1-1", description: "", meta_title: "", meta_description: "", meta_keywords: "", product_category_id: 1, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, avatar_file_name: "image04.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 17062, avatar_updated_at: "2015-05-07 23:06:28"},
  {name: "Категория 1-2", description: "", meta_title: "", meta_description: "", meta_keywords: "", product_category_id: 1, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, avatar_file_name: "image05.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 15982, avatar_updated_at: "2015-05-07 23:06:38"},
  {name: "Категория 1-3", description: "", meta_title: "", meta_description: "", meta_keywords: "", product_category_id: 1, image_file_name: nil, image_content_type: nil, image_file_size: nil, image_updated_at: nil, avatar_file_name: "image04.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 17062, avatar_updated_at: "2015-05-07 23:09:12"}
])
SiteVariable.create!([
  {name: "Код гугл аналитики", value: "", place: "settings"},
  {name: "Код яндекс метрики", value: "", place: "settings"},
  {name: "Номер телефона", value: "+7 123 456 78", place: "footer"},
  {name: "О компании", value: "Текст о компании", place: "footer"},
  {name: "График работы", value: "10:00 - 20:00", place: "header"},
  {name: "Телефон для справки", value: "+7 123 435 456", place: "header"},
  {name: "Содержимое страницы контакты", value: "<p>+7 123 435 456</p>", place: "page_contact"},
  {name: "Информация о компании", value: "Информация о компании здесь", place: "page_company_info"},
  {name: "Доставка и оплата текст", value: "Текст доставки и оплаты", place: "page_delivery_pay"},
  {name: "Текст на главной странице", value: "<p>Инт<strong>ернет магазин детских т</strong>оваров имеет удобный каталог, который позволит вам с легкостью сориентироваться в ассортименте продукции и подобрать замечательную продукцию новорожденным, кроватки, матрасы, горки, батуты, мячи, бассейны, стульчики для кормления, автокресла и много чего другого. Детские товары, предлагаемые магазином в Киеве, отвечают современным стандартам качества, принятым в европейских странах, а также требованиям безопасности. Именно поэтому родители даже могут не сомневаться в том, что продукция, предложенная им, имеет всю нужную документацию от компаний-производителей и, соответственно, магазин предоставляет на любые товары гарантийный срок эксплуатации. В городе Донецк интернет магазин детских товаров предлагает сегодня продукцию как отечественных, так и европейский изготовителей по самой адекватной стоимости. Таким образом, любой клиент, проживающий в Донецке или любом другом украинском городе, сможет подобрать то, что будет ему и его ребенку по душе. При этом клиентами могут стать люди с самыми разными финансовыми возможностями. Товары для детей интернет магазин представляет в удобном каталоге, в котором можно с легкостью сориентироваться и подобрать необходимую модель нужной вещи. Каждый клиент сможет подобрать хорошие товары для детей, прекрасно сочетающие в себе качеству и цену. Помимо того, интернет магазин детских товаров Харьков - это возможность для вас не просто приобрести хорошие вещи. Дело в том, что в каталоге представлены модные коллекции. Не важно, где проживает покупатель, в Харькове или каком-то другом городе, в каталоге он сможет найти такой детский товар, который будет соответствовать современным тенденциям моды.</p>", place: "page_home"},
  {name: "Title", value: "<p>тайтл главной</p>", place: "page_home"},
  {name: "Description", value: "zz", place: "page_home"},
  {name: "Keywords", value: "zz", place: "page_home"},
  {name: "Title", value: "zz", place: "page_contact"},
  {name: "Description", value: "zz", place: "page_contact"},
  {name: "Keywords", value: "zz", place: "page_contact"},
  {name: "Title", value: "zz", place: "page_delivery_pay"},
  {name: "Description", value: "zz", place: "page_delivery_pay"},
  {name: "Keywords", value: "zz", place: "page_delivery_pay"},
  {name: "Блок слайдера", value: "Только качественная продукция", place: "block_in_slider"},
  {name: "Контакты", value: "Здесь будут контакты", place: "footer"}
])
Slide.create!([
  {slider_id: 1, title: "Слайд 1", content: "<h3>Крупный текст</h3>\r\n<p>мелкий текст</p>", avatar_file_name: "banner-1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 444046, avatar_updated_at: "2015-05-08 00:06:59"},
  {slider_id: 1, title: "Слайд 2", content: " <h3>Крупный текст</h3>\r\n<p>мелкий текст</p>", avatar_file_name: "banner-2.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 380405, avatar_updated_at: "2015-05-08 00:07:29"},
  {slider_id: 1, title: "Слайд 3", content: " <h3>Крупный текст</h3>\r\n<p>мелкий текст</p>", avatar_file_name: "banner-3.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 335297, avatar_updated_at: "2015-05-08 00:07:47"},
  {slider_id: 1, title: "Слайд 4", content: " <h3>Крупный текст</h3>\r\n <p>мелкий текст</p>", avatar_file_name: "banner-4.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 755461, avatar_updated_at: "2015-05-08 00:08:41"}
])
Slider.create!([
  {title: "Основной слайдер"}
])
Ckeditor::Picture.create!([
  {data_file_name: "nastol_com_ua_113908.jpg", data_content_type: "image/jpeg", data_file_size: 1186780, assetable_id: 1, assetable_type: "User", type: "Ckeditor::Picture", width: 2048, height: 1153},
  {data_file_name: "nastol_com_ua_113908.jpg", data_content_type: "image/jpeg", data_file_size: 1186780, assetable_id: 1, assetable_type: "User", type: "Ckeditor::Picture", width: 2048, height: 1153}
])
